### PR TITLE
fix: Review model is added

### PR DESCRIPTION
**Pull request by mrandi**
API changed so we need to support it and provide new Review model

BREAKING CHANGE: #79

#79

### CODE REVIEW

**Comment by mrandi** [comment]
we still need to add the documentation here.

**Comment by ahmed-shehata** [comment]
tests?

**Comment by mrandi** [comment]
@ahmed-shehata tests are there and the docs is still missing.

**Comment by artdaw** [comment]
👍

**Comment by ahmed-shehata** [comment]
👍

**Pull request merged**
