### PR TITLE
add simple cache

### PR DESCRIPTION
**Pull request by Gregsen**
add simple cache

### CODE REVIEW

**Comment by Gregsen** [comment]
:+1:

**Comment by Sangdol** [comment]
👍

**Comment by Sangdol** [comment]
👍

**Comment by Gregsen** [comment]
:+1:

**Comment by Sangdol** [comment]
we need to put expiration for the cache in the future. for now, we hotfix.

**Comment by Gregsen** [comment]
:+1:

**Comment by Sangdol** [comment]
👍

**Pull request merged**
